name: tag-stable-release
on:
  release:
    types: [published]

jobs:
  build-image:
    runs-on: [self-hosted, Linux, k8s]
    permissions:
      packages: write
    steps:
      - name: login into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u $ --password-stdin

      - name: Tag latest
        env:
          docker_image_name: ghcr.io/data443/dim-search-web-ui
        run: |
          docker tag ${{ env.docker_image_name }}:${{ github.ref_name }} ${{ env.docker_image_name }}:stable
          docker push --all-tags ${{ env.docker_image_name }}
